const {
  formatForTwitter,
  formatForLinkedIn,
  formatForEmail,
  formatForArticle,
} = require('./platformFormatting');

describe('Platform Formatting', () => {
  const testContent = 'This is a sample #Content for @User.';

  it('formats content for Twitter', () => {
    const result = formatForTwitter(testContent + ' '.repeat(260));
    expect(result.length).toBeLessThanOrEqual(280);
    expect(result).toContain('...');
    expect(result).toMatch(/#content/); // Check lowercase hashtags
  });

  it('formats content for LinkedIn', () => {
    const result = formatForLinkedIn(testContent);
    expect(result).toContain('#Content');
    expect(result).toContain('@User');
  });

  it('formats content for Email', () => {
    const result = formatForEmail('Subject Line\nBody of the email.');
    expect(result.subject).toBe('Subject Line');
    expect(result.body).toBe('Body of the email.');
  });

  it('formats content for Articles', () => {
    const result = formatForArticle('This is the article body.');
    expect(result).toContain('## Article Title');
    expect(result).toContain('This is the article body.');
    expect(result).toContain('*Generated by Content Repurposer Tool*');
  });
});
